"""Add notas field to Producto

Revision ID: 24fbdab8986b
Revises: unique_producto_caja
Create Date: 2024-12-11 16:28:54.592149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24fbdab8986b'
down_revision = 'unique_producto_caja'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caja')
    op.drop_table('bodega')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))
        batch_op.drop_constraint('productos_id_producto_key', type_='unique')
        batch_op.drop_constraint('uq_producto_caja', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_producto_caja', ['id_producto', 'caja_id'])
        batch_op.create_unique_constraint('productos_id_producto_key', ['id_producto'])
        batch_op.drop_column('notas')

    op.create_table('bodega',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('bodega_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_bodega', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ubicacion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='bodega_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bodega_pkey'),
    sa.UniqueConstraint('id_bodega', name='bodega_id_bodega_key'),
    sa.UniqueConstraint('uuid', name='uq_bodega_uuid'),
    postgresql_ignore_search_path=False
    )
    op.create_table('caja',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_caja', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('bodega_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodega.id'], name='caja_bodega_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='caja_pkey'),
    sa.UniqueConstraint('id_caja', name='caja_id_caja_key'),
    sa.UniqueConstraint('uuid', name='uq_caja_uuid')
    )
    # ### end Alembic commands ###
