"""Agregar modelo Pulztag

Revision ID: 259683a02830
Revises: 51211568a969
Create Date: 2024-10-23 22:46:35.663311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259683a02830'
down_revision = '51211568a969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'user'"), nullable=False))

    # ### end Alembic commands ###
