"""Agrego comment a SurveyResponse

Revision ID: 3db2ae61875d
Revises: ab3b1ceffcc6
Create Date: 2025-01-17 15:26:02.943479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db2ae61875d'
down_revision = 'ab3b1ceffcc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
