"""Agregar campos de diseño a Pulzcard

Revision ID: 47dca2673f7c
Revises: bfa6d2598f3b
Create Date: 2025-02-09 20:54:22.538817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47dca2673f7c'
down_revision = 'bfa6d2598f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pulzcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('design_bg_page', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('design_bg_container', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('design_primary', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('design_secondary', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pulzcards', schema=None) as batch_op:
        batch_op.drop_column('design_secondary')
        batch_op.drop_column('design_primary')
        batch_op.drop_column('design_bg_container')
        batch_op.drop_column('design_bg_page')

    # ### end Alembic commands ###
