"""Agregar columna role a User

Revision ID: 51211568a969
Revises: cb9f44a2551e
Create Date: 2024-10-23 13:23:42.456564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51211568a969'
down_revision = 'cb9f44a2551e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')
    
    # ### end Alembic commands ###