"""Añadir campo de plantilla a Pulzcard

Revision ID: 9e8628017ae6
Revises: 
Create Date: 2024-11-18 16:47:52.005626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8628017ae6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Agregar la columna con valor predeterminado
    with op.batch_alter_table('pulzcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template', sa.String(length=20), nullable=False, server_default='template1'))

    # Remover el valor predeterminado
    with op.batch_alter_table('pulzcard', schema=None) as batch_op:
        batch_op.alter_column('template', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pulzcard', schema=None) as batch_op:
        batch_op.drop_column('template')

    # ### end Alembic commands ###
