"""Add image_file column to Pulzcard

Revision ID: a2d81b0c8944
Revises: fd485b434571
Create Date: 2024-10-29 17:59:08.854093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d81b0c8944'
down_revision = 'fd485b434571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pulztag_scan')
    op.drop_table('pulztag')
    with op.batch_alter_table('pulzcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pulzcard', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    op.create_table('pulztag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('default_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('custom_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id')
    )
    op.create_table('pulztag_scan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pulztag_id', sa.INTEGER(), nullable=False),
    sa.Column('scanned_at', sa.DATETIME(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=False),
    sa.ForeignKeyConstraint(['pulztag_id'], ['pulztag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
