"""Added Order model and updated User model

Revision ID: aaf2cbe40232
Revises: bf8acfb984e7
Create Date: 2024-10-11 13:12:06.714127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf2cbe40232'
down_revision = 'bf8acfb984e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_ordered', sa.DateTime(), nullable=False),
    sa.Column('dispositivo', sa.String(length=100), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logos', sa.String(length=500), nullable=True),
    sa.Column('excel_file', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('full_name')

    op.drop_table('order')
    # ### end Alembic commands ###
