"""Inicializar base de datos

Revision ID: cb9f44a2551e
Revises: aaf2cbe40232
Create Date: 2024-10-17 16:35:36.167454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9f44a2551e'
down_revision = 'aaf2cbe40232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('full_name')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=True))

    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_ordered', sa.DATETIME(), nullable=False),
    sa.Column('dispositivo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('mensaje', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('logos', sa.VARCHAR(length=500), nullable=True),
    sa.Column('excel_file', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
