"""Agregar modelo PulztagScan

Revision ID: fd485b434571
Revises: 259683a02830
Create Date: 2024-10-23 23:00:47.266036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd485b434571'
down_revision = '259683a02830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pulztag_scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pulztag_id', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['pulztag_id'], ['pulztag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pulztag_scan')
    # ### end Alembic commands ###
